### ISSUE TITLE
Failure when Publishing multiple items

### ISSUE THREAD

**Issue by ccoffrin** [coursera/courseraprogramming#64] opened 2016-08-11 06:14 UTC
I have observed when publishing multiple items using `--additional-items`, if publishing fails on any one of the items, the remaining items are not processed.

**Comment by nrhodes** [comment] 2016-08-29 18:49
I'm unable to reproduce this problem. Can you post a log showing one of the publishing failing, with other items not subsequently being published?

**Comment by ccoffrin** [comment] 2016-08-30 01:08
Here is an example from one course I am working on,

```
courseraprogramming publish THkzKaBPEeWm9xJA1YXcWQ FktbJ   --additional-items TvXJx npnKe sUgcy GywH2 ewEUu 0tD43
INFO:root:Starting publish for item FktbJ in course THkzKaBPEeWm9xJA1YXcWQ
INFO:root:Fetching requied metadata...
INFO:root:Publishing...
INFO:root:Publish complete for item FktbJ in course THkzKaBPEeWm9xJA1YXcWQ
INFO:root:Starting publish for item TvXJx in course THkzKaBPEeWm9xJA1YXcWQ
INFO:root:Fetching requied metadata...
INFO:root:Publishing...
ERROR:root:Unable to find a publishable assignment with item id TvXJx. Maybe there are no changes to publish?
```

My point here is that if any one of the items fails, then I would like it continue to process the later items, not terminate.

**Comment by nrhodes** [comment] 2016-10-14 21:54
I'm sorry, I misread the problem. Thought we were talking about upload, rather than publish.

**Comment by saeta** [comment] 2016-10-17 22:41
Merged fix for this issue, will publish an updated `courseraprogramming` shortly

**Closed as completed by saeta** 2016-10-17 22:41 UTC
